apiVersion: v1
kind: Namespace
metadata:
  name: cache
---
apiVersion: v1
kind: Service 
metadata:
  name: cache
  namespace: cache
spec:
  type: LoadBalancer
  selector:
    app: cache
  ports:
    - nodePort: 
      port: 80
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
  namespace: cache
spec:
  selector:
    matchLabels:
      app: cache
  replicas: 3
  template:
    metadata:
      labels:
        app: cache
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: ejoi-role
                operator: In
                values: ["front"]
      containers:
      - name: cache
        image: giolekva/caching-proxy:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1300m"
            memory: "1Gi"
        ports:
        - containerPort: 8000
        command: ["caching-proxy", "--port=8000", "--proxy-addr=http://contest-web-server.cms.svc:8888", "--pool-size=1000"]
