---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: log-service
  namespace: cms
spec:
  selector:
    matchLabels:
      app: log-service
  replicas: 1
  serviceName: log-service-headless
  template:
    metadata:
      labels:
        app: log-service
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: ejoi-role
      #           operator: In
      #           values: ["back", "front"]
      containers:
      - name: cms
        image: giolekva/ioi-cms:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 29000
        command: ["cmsLogService"]
        args: ["0"]
        # livenessProbe:
        #   tcpSocket:
        #     port: 29000
        #   initialDelaySeconds: 15
        #   periodSeconds: 5
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: proxy-service
  namespace: cms
spec:
  selector:
    matchLabels:
      app: proxy-service
  replicas: 1
  serviceName: proxy-service-headless
  template:
    metadata:
      labels:
        app: proxy-service
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: ejoi-role
      #           operator: In
      #           values: ["back", "front"]
      containers:
      - name: cms
        image: giolekva/ioi-cms:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 28600
        command: ["/bin/sh", "-c"]
        args: ["cmsProxyService -c=10 0"]
        # livenessProbe:
        #   tcpSocket:
        #     port: 28600
        #   initialDelaySeconds: 15
        #   periodSeconds: 5
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scoring-service
  namespace: cms
spec:
  selector:
    matchLabels:
      app: scoring-service
  replicas: 1
  serviceName: scoring-service-headless
  template:
    metadata:
      labels:
        app: scoring-service
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: ejoi-role
      #           operator: In
      #           values: ["back", "front"]
      containers:
      - name: cms
        image: giolekva/ioi-cms:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "2000m"
            memory: "2Gi"
        ports:
        - containerPort: 28500
        command: ["cmsScoringService"]
        args: ["0"]
        # livenessProbe:
        #   tcpSocket:
        #     port: 28500
        #   initialDelaySeconds: 15
        #   periodSeconds: 5
---
# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: checker
#   namespace: cms
# spec:
#   selector:
#     matchLabels:
#       app: checker
#   replicas: 1
#   serviceName: checker-headless
#   template:
#     metadata:
#       labels:
#         app: checker
#     spec:
#       affinity:
#         nodeAffinity:
#           requiredDuringSchedulingIgnoredDuringExecution:
#             nodeSelectorTerms:
#             - matchExpressions:
#               - key: ejoi-role
#                 operator: In
#                 values: ["back", "front"]
#       containers:
#       - name: cms
#         image: giolekva/ioi-cms:latest
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 22000
#         command: ["cmsChecker"]
#         args: ["0"]
#         # livenessProbe:
#         #   tcpSocket:
#         #     port: 22000
#         #   initialDelaySeconds: 15
#         #   periodSeconds: 5
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: evaluation-service
  namespace: cms
spec:
  selector:
    matchLabels:
      app: evaluation-service
  replicas: 1
  serviceName: evaluation-service-headless
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: ejoi-role
      #           operator: In
      #           values: ["back", "front"]
      containers:
      - name: cms
        image: giolekva/ioi-cms:tester
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "2000m"
            memory: "4Gi"
        ports:
        - containerPort: 25000
        command: ["cmsEvaluationService"]
        args: ["0"]
        # livenessProbe:
        #   tcpSocket:
        #     port: 25000
        #   initialDelaySeconds: 15
        #   periodSeconds: 5
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: admin-web-server
  namespace: cms
spec:
  selector:
    matchLabels:
      app: admin-web-server
  replicas: 1
  serviceName: admin-web-server-headless
  template:
    metadata:
      labels:
        app: admin-web-server
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: ejoi-role
      #           operator: In
      #           values: ["front", "back"]
      containers:
      - name: cms
        image: giolekva/ioi-cms:latest
        imagePullPolicy: Always
        # resources:
        #   requests:
        #     cpu: "1000m"
        #     memory: "1Gi"
        ports:
        - containerPort: 8889
        - containerPort: 21100
        command: ["cmsAdminWebServer"]
        args: ["0"]
        # livenessProbe:
        #   tcpSocket:
        #     port: 21100
        #   initialDelaySeconds: 15
        #   periodSeconds: 5
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: contest-web-server
  namespace: cms
spec:
  selector:
    matchLabels:
      app: contest-web-server
  serviceName: contest-web-server
  replicas: 10
  template:
    metadata:
      labels:
        app: contest-web-server
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: ejoi-role
      #           operator: In
      #           values: ["front", "back"]
      containers:
      - name: cms
        image: giolekva/ioi-cms:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "500m"
            memory: "300Mi"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 8888
        - containerPort: 21000
        command: ["/bin/sh", "-c"]
        args: ["export INDEX=${POD_NAME#contest-web-server-} && cmsContestWebServer -c=10 $INDEX"]
        # livenessProbe:
        #   tcpSocket:
        #     port: 21000
        #   initialDelaySeconds: 15
        #   periodSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cws
  namespace: cms
spec:
  selector:
    matchLabels:
      app: cws
  replicas: 1
  template:
    metadata:
      labels:
        app: cws
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: ejoi-role
      #           operator: In
      #           values: ["front", "back"]
      containers:
      - name: cms
        image: giolekva/ioi-cms:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "500m"
            memory: "300Mi"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 8888
        - containerPort: 21000
        command: ["/bin/sh", "-c"]
        args: ["export INDEX=${POD_NAME#contest-web-server-} && cmsContestWebServer -c=ALL 0"]
        # livenessProbe:
        #   tcpSocket:
        #     port: 21000
        #   initialDelaySeconds: 15
        #   periodSeconds: 5
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tester
  namespace: cms
spec:
  selector:
    matchLabels:
      app: tester
  serviceName: tester-headless
  replicas: 58
  template:
    metadata:
      labels:
        app: tester
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: ejoi-role
                operator: In
                values: ["tester"]
      containers:
      - name: cms
        image: giolekva/ioi-cms:tester
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1300m"
          limits:
            cpu: "2000m"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 8888
        - containerPort: 26000
        securityContext:
          privileged: true
        command: ["/bin/sh", "-c"]
        args: ["export INDEX=${POD_NAME#tester-} && cmsWorker $INDEX"]
        # livenessProbe:
        #   tcpSocket:
        #     port: 26000
        #   initialDelaySeconds: 15
        #   periodSeconds: 5
      tolerations:
      - key: "key"
        operator: "Equal"
        value: "value"
        effect: "NoSchedule"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rws
  namespace: cms
spec:
  selector:
    matchLabels:
      app: rws
  replicas: 1
  template:
    metadata:
      labels:
        app: rws
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: ejoi-role
      #           operator: In
      #           values: ["front", "back"]
      containers:
      - name: cms
        image: giolekva/ioi-cms:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "500m"
            memory: "300Mi"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 8890
        command: ["/bin/sh", "-c"]
        args: ["cmsRankingWebServer --config=/usr/local/etc/ranking.conf"]
        # livenessProbe:
        #   tcpSocket:
        #     port: 21000
        #   initialDelaySeconds: 15
        #   periodSeconds: 5
