kind: Pod
apiVersion: v1
metadata:
  name: db-init
  namespace: cms
spec:
  containers:
  - name: db-init
    image: giolekva/ioi-cms:latest
    imagePullPolicy: Always
    command: ["/bin/sh"]
    args: ["-c", "cmsInitDB"]
  restartPolicy: Never
