kind: Pod
apiVersion: v1
metadata:
  name: download-submissions
  namespace: default
spec:
  containers:
  - name: download
    image: giolekva/ioi-cms:download
    imagePullPolicy: Always
    command: ["/bin/sh"]
    args: ["-c", "/scripts/download-submissions.sh $CONTEST_ID"]
  restartPolicy: Never
