---
apiVersion: v1
kind: Service 
metadata:
  name: web
  namespace: cms
spec:
  type: LoadBalancer
  selector:
    app: cms
  ports:
    - name: web
      port: 80
      targetPort: 8888
    - name: admin
      port: 81
      targetPort: 8889
